version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # depends_on:
    #   - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true  # Helps with hot-reloading in Docker
    depends_on:
      - backend